name: Build CI

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    types: [rerequested]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 1
    - name: esp-idf setup/install
      run: esp-idf/install.sh
    - name: build DOOM
      run: |
        make
    - uses: actions/upload-artifact@v3
      with:
        name: s3-boy-doom-combined
        path: fw/s3-boy-doom/build/s3-boy-doom-combined.bin
